### PR TITLE
docs: Create 2023-11-remove-reverse-sshnp-client.md

### PR DESCRIPTION
**Pull request by xavierchanth**
**- What I did**

- Added a new decision as a draft
- I was asked to make this log as a result of discussions that took place last sprint.

**- How I did it**

**- How to verify it**

**- Description for the changelog**
docs: Create 2023-11-remove-reverse-sshnp-client.md

### CODE REVIEW

**Review by gkc — DISMISSED** [review]
Yes please! LGTM

**Comment by xavierchanth** [comment]
Currently the status is draft, should we finalize before merging @gkc @cpswan ?

**Comment by cpswan** [comment]
@XavierChanth yes, as it's been discussed in arch, 1-2-1 calls and the eng gChat I think we're OK to review it as final.

**Comment by xavierchanth** [comment]
@cpswan feel free to approve and merge

**Review by cpswan — APPROVED** [review]

**Pull request merged**
